Update README sub actions
The README reference a deprecated action for setup-ruby `actions/setup-ruby@v1` which if used would return the following error in your workflow:

```
Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.6 not found
```

This has been replaced with `ruby/setup-ruby@v1` as referenced here https://github.com/ruby/setup-ruby#single-job

This commit also bumps the actions version for `actions/checkout` and `actions/cache` to reference the latest.